name:                templateAnalysis
version:             0.1.0.0
github:              "githubuser/templateAnalysis"
license:             BSD3
author:              "Solrun Einarsdottir"
maintainer:          "slrn@chalmers.se"
copyright:           "2022 Solrun Einarsdottir"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/templateAnalysis#readme>

dependencies:
- base >= 4.7 && < 5
- twee-lib == 2.4
- containers
- pretty
- dir-traverse
- directory
- filepath
library:
  source-dirs: src

#executables:
#  templateAnalysis-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - templateAnalysis

tests:
  templateAnalysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templateAnalysis
